/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hashemnombres;

import java.awt.Toolkit;
import java.util.HashMap;

/**
 *
@author JOSUÉ DANIEL REYNA ROLDÁN OCHOA
 */
public class TablaNombres extends javax.swing.JFrame {
  
private HashMap<String,String> hashMap= new HashMap<String,String>();
    /**
     * Creates new form TablaNombres
     */
    public TablaNombres() {
        initComponents();
        setIconImage(Toolkit.getDefaultToolkit().getImage(this.getClass().getResource("/org/img/lion.png")));  
        hashMap.put("07", "1");
        hashMap.put("06", "2");
        hashMap.put("05", "3");
        hashMap.put("04", "4");
        hashMap.put("03", "5");
        hashMap.put("02", "6");
        hashMap.put("01", "7");
        hashMap.put("00", "8");
        
        hashMap.put("17", "9");
        hashMap.put("16", "10");
        hashMap.put("15", "11");
        hashMap.put("14", "12");
        hashMap.put("13", "13");
        hashMap.put("12", "14");
        hashMap.put("11", "15");
        hashMap.put("10", "16");
        
        hashMap.put("27", "17");
        hashMap.put("26", "18");
        hashMap.put("25", "19");
        hashMap.put("24", "20");
        hashMap.put("23", "21");
        hashMap.put("22", "22");
        hashMap.put("21", "23");
        hashMap.put("20", "24");
        
        hashMap.put("37", "25");
        hashMap.put("36", "26");
        hashMap.put("35", "27");
        hashMap.put("34", "28");
        hashMap.put("33", "29");
        hashMap.put("32", "30");
        hashMap.put("31", "31");
        hashMap.put("30", "32");
        
        hashMap.put("47", "33");
        hashMap.put("46", "34");
        hashMap.put("45", "35");
        hashMap.put("44", "36");
        hashMap.put("43", "37");
        hashMap.put("42", "38");
        hashMap.put("41", "39");
        hashMap.put("40", "40");
        
        hashMap.put("57", "41");
        hashMap.put("56", "42");
        hashMap.put("55", "43");
        hashMap.put("54", "44");
        hashMap.put("53", "45");
        hashMap.put("52", "46");
        hashMap.put("51", "47");
        hashMap.put("50", "48");
        
        hashMap.put("67", "49");
        hashMap.put("66", "50");
        hashMap.put("65", "51");
        hashMap.put("64", "52");
        hashMap.put("63", "53");
        hashMap.put("62", "54");
        hashMap.put("61", "55");
        hashMap.put("60", "56");
        
        hashMap.put("77", "57");
        hashMap.put("76", "58");
        hashMap.put("75", "59");
        hashMap.put("74", "60");
        hashMap.put("73", "61");
        hashMap.put("72", "62");
        hashMap.put("71", "63");
        hashMap.put("70", "64");
        
        hashMap.put("87", "65");
        hashMap.put("86", "66");
        hashMap.put("85", "67");
        hashMap.put("84", "68");
        hashMap.put("83", "69");
        hashMap.put("82", "70");
        hashMap.put("81", "71");
        hashMap.put("80", "72");
        
        
        
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private String buscar(String val){
    String result=null;
    result=hashMap.get(val);
    if(result==null){
    result="ninguno";
    }
    return result;
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("72 Nombres de Hashem");
        setResizable(false);

        jTable1.setBackground(new java.awt.Color(0, 0, 0));
        jTable1.setFont(new java.awt.Font("Arial", 1, 55)); // NOI18N
        jTable1.setForeground(new java.awt.Color(204, 204, 0));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"כהת", "אכא", "ללה", "מהש", "עלם", "סיט", "ילי", "והו"},
                {"הקם", "הרי", "מבה", "יזל", "ההע", "לאו", "אלד", "הזי"},
                {"חהו", "מלה", "ייי", "נלך", "פהל", "לוו", "כלי", "לאו"},
                {"ושר", "לכב", "אום", "ריי", "שאה", "ירת", "האא", "נתה"},
                {"ייז", "רהע", "חאם", "אני", "מנד", "כוק", "להח", "יחו"},
                {"מיה", "עשל", "ערי", "סאל", "ילה", "וול", "מיכ", "ההה"},
                {"פוי", "מבה", "נית", "ננא", "עמם", "החש", "דני", "והו"},
                {"מחי", "ענו", "יהה", "ומב", "מצר", "הרח", "ייל", "נמם"},
                {"מום", "היי", "יבם", "ראה", "חבו", "איע", "מנק", "דמב"}
            },
            new String [] {
                "", "", "", "", "", "", "", ""
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.setIntercellSpacing(new java.awt.Dimension(3, 4));
        jTable1.setRowHeight(55);
        jTable1.setRowSelectionAllowed(false);
        jTable1.setSelectionBackground(new java.awt.Color(0, 0, 0));
        jTable1.setSelectionForeground(new java.awt.Color(204, 204, 0));
        jTable1.getTableHeader().setReorderingAllowed(false);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
            jTable1.getColumnModel().getColumn(4).setResizable(false);
            jTable1.getColumnModel().getColumn(5).setResizable(false);
            jTable1.getColumnModel().getColumn(6).setResizable(false);
            jTable1.getColumnModel().getColumn(7).setResizable(false);
        }

        jMenu1.setText("INFO");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1008, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 505, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
    int selectedRow = jTable1.getSelectedRow();
    int selectedColumn = jTable1.getSelectedColumn();     
    String value= selectedRow+""+ selectedColumn;
   
  //  System.out.println(buscar(value));
    String v=buscar(value);
  //System.out.println(v);
    if(v=="ninguno"){}else{
  //  new JFrameImagen(v).setVisible(true);
    new Magen(v).setVisible(true);
    }
          
          
    
jTable1.getSelectionModel().clearSelection();
// TODO add your handling code here:
    }//GEN-LAST:event_jTable1MouseClicked

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked

        new INFO().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TablaNombres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TablaNombres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TablaNombres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TablaNombres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TablaNombres().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
